name: Validate YAML Schema

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pajv
        run: npm install -g pajv
      - name: Test schemas
        run: for v in `ls rules/*.yml`; do echo "Testing $v" && pajv test -s schema.json -d $v --valid ; done
