name: Validate YAML Schema

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.1
        with:
          comment: "true"
          base_dir: "rules"
          json_schema: "schema.json"
