name: Validate YAML Schema

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: InoUno/yaml-ls-check@develop
        with:
          root: data
          schemaMapping: |
          {
            "schema.json": [ "rules/*.yml" ]
          }
