name: Release rules

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  upload-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: json-yaml-validate
        uses: GrantBirki/json-yaml-validate@v2.6.1
        with:
          comment: "true"
          base_dir: "./rules"
          json_schema: "schema.json"
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Create rules file
        run: python misc/release.py
      - name: Upload versions
        uses: softprops/action-gh-release@v1
        with:
          files: rules.yml
